---
prompts:
  default: system_prompt.txt
  #private: L:\computer\prompts\private_prompt.txt
  #code: L:\computer\prompts\code_prompt.txt
history:
  enabled: true
  file: 'L:\computer\my_history.txt'
agent:
  prompts:
    - default
   # - private
  temperature: 0
  name: Computer
  max_tries: 3
  sleep_seconds_between_tries: 2
  agent_type: conversational-react-description
  max_iterations: 4
  tools_enabled: true
phrases:
  exit:
    - q
    - exit
    - quit
    - fuck off
pre-parsers:
  clipboard: { enabled: true }
  time: { enabled: true }
tools:
  bing_search: { enabled: true }
  bing_news: { enabled: true }
  wttr_weather: { enabled: true }
  wikipedia: { enabled: true }
  google_search: { enabled: true }
  clear_memory: { enabled: true }
  date_time_tool: { enabled: true }
  input_switch: { enabled: true }
  available_models: { enabled: true }
  model_switch: { enabled: true }
  end_conversation: { enabled: true }
  enable_disable_tools: { enabled: true }
  output_switch: { enabled: true }
  ics_calendar:
    enabled: true
    config_file: 'L:\computer\my_calendar.yaml'
user:
  location: Germany, Berlin
  name: Master
  # timezone: UTC # optional
models:
  groq:
    provider: groq
    model: llama3-70b-8192
    synonyms:
    - llama 70
    - fastest
    - cheapest
  gpt3:
    provider: openai
    model: gpt-3.5-turbo
    temperature: 1.9
    synonyms: ["gpt 3", "gpt-3"]
  zalando:
    provider: openai_custom
    model: bedrock/mistral.mistral-large-2402-v1:0
    base_url: http://localhost:1234
    synonyms: ["local"]

  lmstudio:
    provider: lm_studio
    model: current
    synonyms: ["local"]
    tools_enabled: false
  ollama:
    provider: ollama
    model: llama3:latest
    synonyms: ["private", "secure"]
  gpt4o:
    provider: openai
    model: gpt-4o
    synonyms: ["gpt 4o", "gpt 4 o", "newest", "latest"]
  gpt4:
    provider: openai
    model: gpt-4
    synonyms: ["gpt 4", "gpt-4"]
  mistral:
    provider: mistral
    model: mistral-large-latest
    agent_type: zero-shot-react-description
    synonyms: ["mixtral"]
  code:
    provider: mistral
    model: open-mixtral-8x22b
    tools_enabled: false
    prompts:
      - code
  # check if gemini is allowed in your country.
  google:
    provider: google
    model: gemini-1.5-flash-latest
    synonyms: ["gemini"]
io_input:
  text:
    provider: text
  listen:
    synonyms:
      - ispeak
    provider: deepgram
    model: nova-2
    punctuate: true
    language: en-US
    encoding: linear16
    channels: 1
    sample_rate: 16000
    endpointing: 300
    smart_format: true
io_output:
  write:
    provider: text
  speak:
    synonyms:
      - talk
    provider: deepgram
    performance: some
    encoding: linear16
    sample_rate: 24000
    model: aura-helios-en
