---
# Point .env COMPUTER_CONFIG_FILE to this file. Like so:
# -- .env --
# COMPUTER_CONFIG_FILE=PATH_TO\computer\examples\1_minimal_groq\my_config.yaml
prompts:
  default: system_prompt.txt
history:
  enabled: false
agent:
  name: "Bobik"
  prompts: ["default"]
phrases:
  exit: ["q", "exit"]
  with_tools: ["agent"]
  no_tools: ["llm"]
user:
  location: Germany, Berlin
models:
  groq:
    provider: groq
    model: llama3-70b-8192
io_input:
  text:
    provider: text
io_output:
  write:
    provider: text
