---
# Point .env COMPUTER_CONFIG_FILE to this file. Like so:
# -- .env --
# COMPUTER_CONFIG_FILE=PATH_TO\computer\examples\2_minimal_groq_with_voice\my_config.yaml
prompts:
  default: system_prompt.txt
history:
  enabled: false
agent:
  prompts:
    - default
  temperature: 0
  name: Bobik
  max_tries: 3
  sleep_seconds_between_tries: 2
  agent_type: conversational-react-description
  max_iterations: 4
  tools_enabled: true
phrases:
  exit:
    - q
    - exit
  with_tools:
    - agent
  no_tools:
    - llm
user:
  location: Germany, Berlin
  name: Master
models:
  groq:
    provider: groq
    model: llama3-70b-8192
io_input:
  text:
    provider: text
  listen:
    provider: deepgram
    model: nova-2
    punctuate: true
    language: en-US
    encoding: linear16
    channels: 1
    sample_rate: 16000
    endpointing: 300
    smart_format: true
io_output:
  write:
    provider: text
  speak:
    synonyms: ["talk"]
    provider: deepgram
    performance: some
    encoding: linear16
    sample_rate: 24000
    model: aura-helios-en
